### ISSUE TITLE
missing cluster label in 'clips' view

### ISSUE THREAD

**Issue by droumis** [magland/mountainlab#117]
Log message:

2016-12-09 15:58:32.924: Error: Unable to initialize multiscaletimeseries.... path is empty.

**Comment by magland** [comment]
Could you give some more details? What were you trying to do here...

**Comment by droumis** [comment]
when viewing the 'clips', are there supposed to be cluster labels on each clip? It looked like the clips were from all the clusters, so it was unclear to me and Loren how to associate clip to cluster.

**Comment by magland** [comment]
You are right. The functionality for clip view is not complete. We will put this on our to do list, along with the following very useful missing functionality:
click on a clip and move to the corresponding time sample in the timeseries view.
