### ISSUE TITLE
compile error on EL7/gcc4.8.5 due to PRIi32

### ISSUE THREAD

**Issue by ahbarnett** [magland/mountainlab#134]
To get compile_components.sh to work I needed to edit out the PRIi32 in the printf statement
line 119 of mdaio.cpp and make it a plain %d.
Some #define is probably supposed to replace this but it mustn't have worked.
I still got warnings in other places due to same PRIi32.
I use qt 5.8, but pretty old GCC 4.8.5.

Here's the error before I fixed it:

g++ -c -pipe -O2 -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -DUSE_REMOTE_READ_MDA -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../include -I../include/mda -I../include/cachemanager -I../include/taskprogress -I../include/mlnetwork -I../include/componentmanager -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I../build -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/taskprogress.o taskprogress/taskprogress.cpp
mda/mdaio.cpp: In function ‘bigint mda_read_header(MDAIO_HEADER*, FILE*)’:
mda/mdaio.cpp:119:72: error: expected ‘)’ before ‘PRIi32’
                 printf("mda_read_header: Dimension %ld less than 0: %" PRIi32 "\n", i + 1, dim0);
                                                                        ^
mda/mdaio.cpp:119:96: warning: spurious trailing ‘%’ in format [-Wformat=]
                 printf("mda_read_header: Dimension %ld less than 0: %" PRIi32 "\n", i + 1, dim0);
                                                                                                ^
mda/mdaio.cpp:119:96: warning: too many arguments for format [-Wformat-extra-args]

Cheers, Alex

**Comment by magland** [comment]
Okay, this should now be fixed in the latest master.
