### ISSUE TITLE
adjacency_matrix.mda output a plain text file, not.mda

### ISSUE THREAD

**Issue by Hanlin-Zhu** [magland/mountainlab#142]
Hi mountainlab team,

     I am trying to use your software to do spike sorting, the software works fine when electrode location information is not specified. However, I am getting strange errors running "branch_cluster_v2" , the erro message is "incompatible dimensions between AM and X   1x1 28". Then I looked at where adjacency_matrix.mda is stored in my PC (in the output folder). It seems that unlike firings.mda, this mda is stored as a plain text file, .mda is just part of its name.  Next I checked geom2adj.processor.cpp. It seems that Y.write32(output) created this mda. Could this be the problem? I saw that in creating firings.mda, write64 is used and it works, so maybe you want to send me a new compiled geom2adj_processor.o with Y.wirte64?  Thanks a lot.

**Comment by magland** [comment]
Hi. Indeed you are noticing some quirks regarding storing the adjacency matrix. But you seem to be using an older version of the sorting pipeline. Could you please instead use the latest pipeline which is: mountainsort_002.pipeline? That will make it easier for us to assist you. This is as described here: https://github.com/magland/mountainlab/blob/master/doc/the_first_sort.md.

**Comment by Hanlin-Zhu** [comment]
Thanks for your prompt reply, the problem is indeed solved.
