### ISSUE TITLE
Relationship with Kilosort

### ISSUE THREAD

**Issue by Hanlin-Zhu** [magland/mountainlab#143]
This might seems to be little irrelevant, but I searched "kilosort" in your repository and it returned some pipeline instruction. May I know what's the relationship between mountainsort and kilosort (https://github.com/cortex-lab/KiloSort) ? Thanks !

**Comment by magland** [comment]
There is a plugin to run kilosort within mountainlab. In this way, various methods may be compared within a single platform.

**Comment by magland** [comment]
Here's the plugin with instructions:
https://github.com/magland/ml_kilosort
