### ISSUE TITLE
Out of memory compilation error

### ISSUE THREAD

**Issue by jchutrue** [magland/mountainlab#144]
I got an error while compiling the ms3 branch--make complained that memory had been exhausted. I fixed this by changing the line `make -j` in compile_components.sh to `make -j4` according to my machine's specs:

OS: Ubuntu 16.04.2
Memory: 12 GB RAM
Swap: 12 GB
Total disk space: 512 GB SSD
Processor: Intel Core i7 2.50 GHz x 4

**Comment by wysota** [comment]
I pushed a fix that attempts to auto-detect the number of jobs to run. See if it works.

**Comment by jchutrue** [comment]
Looks good!
