### ISSUE TITLE
Converting ntt files into mda

### ISSUE THREAD

**Issue by mgarcia7** [magland/mountainlab#145]
Can the mdaconvert command-line utility convert ntt files? If not, what would be the best way to go about this? I know I can convert the ntt format into a MATLAB matrix with dimensions Sample Number x Channel x Timestamp, but I'm not sure what my next steps would be. Thanks!

**Comment by magland** [comment]
mdaconvert does not yet have that ability, but I'd like to add it if it
will be helpful.

Could you clarify a bit... does the .ntt file contain the raw data from the
acquisition device? I'm confused when you say the dimensions are Sample
Number x Channel x Timestamp.  Wouldn't the dimensions be something like
 N_samples x N_channels? and a separate vector with the timestamps?

How complicated is the script to load into matlab?

Thx, Jeremy

**Comment by mgarcia7** [comment]
Yes, the .ntt file contains the raw data. When you load the data into MATLAB using the Neuralynx provided conversion function, you get a matrix with dimensions N_samples x N_channels x N_spike, and a separate Timestamps vector (I was  off about that in my original post - sorry!). Each N_spike dimension corresponds to a timestamp.

**Comment by magland** [comment]
Okay thanks. Do you have the script or library that loads .ntt into MATLAB?
Jeremy

**Comment by mgarcia7** [comment]
Attached are the Neuralynx functions - the specific one that I use is Nlx2MatSpike. Since these are pre-compiled binaries and I assume you want to be able to look at the code, I've also attached a function that can be used to convert an ntt file into a matlab data structure. 
[MatlabImportExport_v6.0.0.zip](https://github.com/magland/mountainlab/files/1206194/MatlabImportExport_v6.0.0.zip)

[read_ntt_files.zip](https://github.com/magland/mountainlab/files/1206243/read_ntt_files.zip)

**Comment by magland** [comment]
Thanks. I'll try to get to this, but not sure exactly when.

**Comment by magland** [comment]
I am closing this for now but would certainly like to get to it at some point. Or maybe somebody else could take the initiative and I can provide guidance.
