### ISSUE TITLE
Accept additional timestamp input file corresponding to raw data

### ISSUE THREAD

**Issue by kemerelab** [magland/mountainlab#146]
The data points in my raw mda files are not uniformly sampled (i.e. there are gaps). It would be nice if mountainsort could accept another input file containing the timestamps corresponding to the raw mda file. I don't know if mountainsort interpolates, but that would also be a valid option to take care of the missing data issue.

**Comment by jchutrue** [comment]
In addition, if the output firings.mda were relative to the timestamp file, this would facilitate the merging of raw data chunks for which their temporal relationships are known. As an example use case, we might have _n_ raw.mda.prv files (with each file having a corresponding timestamp file) over the course of a 24-hr period, and we want to sort over that entire period.

**Comment by magland** [comment]
Could you explain more about what types of gaps there are? Are they 1ms gaps? 10 minute gaps? And how often do they occur throughout the dataset?

Regarding the second point, this is a very standard situation, and I believe this should be handled in a layer above. I am working on designing such a system.

**Comment by jchutrue** [comment]
The gaps are on the order of tens of milliseconds and generally occur at the beginning of a data file due to recording hardware initializations. For a 2 hour file, we don't usually see more than 1 second total of gaps at a sampling rate of 30 kHz.

**Comment by magland** [comment]
In my opinion (with such small gaps) there should be a preprocessing
function that fills the gaps with zeros. Then that preprocessed file would
be input into the sorting pipeline. Let me know if you would like help
creating such a utility -- and I am sure it will be useful to others.

**Comment by ckemere** [comment]
Zeros are slightly incorrect, right? Ideal would be NaNs, I think? Is there a NaN in the int16 space?

**Comment by jchutrue** [comment]
Yes--zeros can be legitimate values. If mountainsort expects uniformly sampled data points, interpolation might be the way to go

**Comment by magland** [comment]
It is tricky. If we were to use NaN or some other value that codes NaN then
the subsequent processors (bandpass_filter, whiten, etc) would need to
respect it, adding undesirable complexity. A disadvantage of filling with
zeros is that it could cause big oscillations after the bandpass filter as
the baseline could be very far from zero. Therefore the ideal time to set
zeros is after the bandpass filter. Whitening keeps zeros as zeros.

I am not sure how interpolation would work. If a few milliseconds were
missing, what would the interpolated value be?

I am not sure I know the best solution at this point.

**Comment by ckemere** [comment]
I need to read up on the artifact masking feature (I haven't learned enough to understand how it works yet). Missing data could be incorporated at this step somehow.

It is definitely the case that zeros are a less than ideal padding (because the nearby values are unlikely to be zero). Linear interpolation is the easiest thing to implement. Will look further into the preprocessing step idea.

**Comment by magland** [comment]
I thought some more about it and the following are what I consider the two cleanest solutions (ultimately, I should not be making the decisions but rather providing the tools)...

The first is to fill gaps with zeros *after* bandpass filter. In my opinion filling with zeros rather than interpolating is much better (once the data has been filtered so that the sliding mean is essentially zero). This is the easiest because nothing else needs to be changed.

The second possibility is to run the entire processing without filling in the gaps (treating it like uniform) and then remapping the results at the end with some kind of additional text file (same way to handle the multiple sessions within a day). Also, we can simply throw away spikes that span one of the gaps. The possible drawbacks are:

* abrupt jumps at the gaps cause oscillations from filtering (but not nearly as bad as filling with zeros)
* requires extra book-keeping

**Comment by ckemere** [comment]
Why not linearly interpolate? This will make the intervening data low frequency and unlikely to generate artifacts post-filtering. I like the idea of zeroing after filtering, but it might not be necessary.

Eventually, good bookkeeping is probably the right answer. For now, I think it's not critical?

**Comment by magland** [comment]
![zerofill-or-interp](https://user-images.githubusercontent.com/3679296/28475319-ad5a6586-6e19-11e7-857c-66c6bdbc7d27.png)

This is the picture I have in mind between zero filling and linear interpolation. From this view, I'd prefer the zero filling.

**Comment by ckemere** [comment]
I'm going to ask @jchutrue to give me some actual data to look at. My guess is that because of 1/f, after filtering the linear interpolation will look better (i.e., fewer artifacts). It still is an abrupt change, regardless, though, so it may not make a huge difference.

**Comment by jchutrue** [comment]
@ckemere I just shared a linear track session data with you. Using GDrive so @magland hopefully it works for you too if you want to take a look

**Comment by magland** [comment]
@jchutrue for convenience, would it be possible to also share a small subset of that dataset? It is 22GB. Maybe a 10-20MB time segment to get a sense of it? Also, should there be an accompanying .txt file describing the sampling? So we know where the time gaps are? Thx.

**Comment by jchutrue** [comment]
@magland 1 minute of data is already about 300 MB. But what I can do is give you just one tetrode; that should be about 15 MB.

**Comment by magland** [comment]
Sounds good. I'll wait until i get the google drive notification.

**Comment by jchutrue** [comment]
@magland truncated the original data to about one minute and just shared with you. There's a timestamps file included that contains the sample indices for the raw data. You can find the gaps by taking the diff of the timestamps and looking for values that are > 1

**Comment by magland** [comment]
Thanks @jchutrue . I took a look at it and have a better idea about it now.

I think there are two situations: (a) large gaps. (b) small gaps

For (a) I recommend ignoring them during sorting and then doing book-keeping for re-mapping the spike timestamps after spike sorting

For (b) I recommend we create a (preprocessing) utility for filling in the missing data using one of the following options (command-line parameter):
* fill with zeros
* linear interpolate
* fill with constant value that is equal to the estimated baseline

mp-run-process mountainsort.fill_gaps --timeseries=raw.mda --timeseries_out=raw2.mda --timestamps=file.mda --method=fill_with_constant

what do you think?

**Comment by jchutrue** [comment]
@magland That sounds fine to me, especially having different options for the interpolation method

**Comment by magland** [comment]
This is somewhat related to an issue raised by Elizabeth on the slack team page. I am closing this for now but we should follow up. Maybe somebody will take some initiative and I can provide guidance. Especially since the processor plugins can be written in more accessible python now.
