### ISSUE TITLE
TODO: add user warning/hint if fftw3 package is not present

### ISSUE THREAD

**Issue by magland** [magland/mountainlab#153]
@wysota : as we discussed. The following needs testing and integration into the .pro:

```
!contains(CONFIG, "no_fftw3"):!packagesExist(fftw3) {
  message(FFTW3 does not seem to be on your system in the standard location. Please install it.)
  message(Alternatively, you can disable fftw3 (which will disable some functionality), you can make a .qmake.cache file in this directory with the following line:)
  message(CONFIG += no_fftw3)
  error(You can also use .qmake.cache to provide other qmake settings that may allow you to find fftw in a different location)
}
```

**Comment by wysota** [comment]
Implemented.

**Comment by magland** [comment]
Looks good. The only concern I have is how reliably packagesExist(fftw3) is? I would not want that to return false when fftw3 is found in a nonstandard place. Because then the user would have no path forward but to remove this test in the .pro file. Thoughts?

**Comment by wysota** [comment]
It relies on pkg-config. If fftw3 is in a non-standard place, we wouldn't detect it during compilation anyway (unless PKG_CONFIG_PATH is set correctly or the user manually modifies appropriate entries in the .pro file). Ultimately I'll try to provide something 'smart' to handle compilation as well (I already have an idea how to do it). So I'd settle for what we have now for the time being and then we'll replace it with the final approach.

**Comment by magland** [comment]
Okay sounds good. closing
