### ISSUE TITLE
geom.csv specification

### ISSUE THREAD

**Issue by nikolaskaralis** [magland/mountainlab#159]
What are the units that geom.csv expects? Micrometers?
I guess this should be the same units as for the adjacency radius.

What about channels that are supposed to be ignored? How can one define them?

I couldn't find this information in the documentation.

**Comment by jasonechung** [comment]
As long as the geom.csv and adjacency_radius match, it does not matter, though we have typically been using microns.

To ignore specific channels, we have been selecting the subset of channels to sort using the channels flag. This is also helpful if people have subsets of a larger .mda file to sort separately. For example, if we had a tetrode with a dead/noisy channel 3, we would  run with the option:
`--channels=1,2,4`
 Would suggest that this flag would just be appended to the line in your pipelines.txt
