### ISSUE TITLE
Adding mountainlab/bin to PATH environment variable

### ISSUE THREAD

**Issue by Min-SooKANG** [magland/mountainlab#160]
Hi. I'm interested in applying mountainlab with some of my data. 
Before the tryout, I followed the instructions to test if I correctly installed it.
Here comes the problem, I could not make a synthetic data just like the instruction movie did. I end up with some that says:
/example3/raw.mda',
     '--firings_true=/home/ncb/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/firings_true.mda',
     '--M=4',
     '--T=800',
     '--K=16',
     '--duration=1200',
     '--amp_variation_min=0.2',
     '--amp_variation_max=1',
     '--firing_rate_min=0.5',
     '--firing_rate_max=3',
     '--noise_level=1' ] }
Error in system call. Please be sure that mountainlab/bin is in your path.

so I tried to add the path as instructed by typing, 
export PATH=/path/to/mountainlab/bin:$PATH
but this won't help!
Is there a specific solution to this problem? I'm not that used to using Linux by the way.

Min Soo

**Comment by jasonechung** [comment]
Hi Min Soo,

Did you install mountainsort in your home directory? 
The path to where you installed mountainlab should be used in the command

`export PATH=/ / / /mountainlab/bin:$PATH`

If you installed in your home directory, the specific path will change depending on your username for your computer, taking the form of something like:

`export PATH=/home/YOUR-USER-NAME-HERE/mountainlab/bin:$PATH`

**Comment by Min-SooKANG** [comment]
Thank you for the kind reply!It works well! Thank you again!Best, Min Soo
------ Original Message ------
Date: Wednesday, Sep 20, 2017 11:19:16 PM
