### ISSUE TITLE
kron-run command and directory

### ISSUE THREAD

**Issue by liciadep** [magland/mountainlab#162]
Hi. I'm trying to install Mountain lab to sort some of my data.
We are not sure on how to execute the kron-run command and in which directory.
We had this kind of error message:
RP720316:kron depropris.licia$ kron-run ms3 example1 cd examples/003_kron_mountainsort_nodaemon
-bash: kron-run: command not found
RP720316:kron depropris.licia$ ./001_generate_synthetic_data.sh
-bash: ./001_generate_synthetic_data.sh: No such file or directory

How can we fix this issue?

Thanks!

**Comment by magland** [comment]
Did you follow the installation instructions including adding mountainlab/bin to your path? There is a symbolic link file called kron-run found in the mountainlab/bin directory.

**Comment by liciadep** [comment]
I tryied to double click on the link and i got this answer

Last login: Wed Sep 20 11:02:23 on ttys002
RP720316:~ depropris.licia$ /Users/depropris.licia/Documents/GitHub/feel-free/mountainlab/kron/kron-run ; exit;
env: nodejs: No such file or directory
logout

[Process completed]

What do you think?

**Comment by magland** [comment]
Note the following in the installation instructions:

Note: depending on how nodejs is named on your system, you may need to do the following (or something like it):
sudo  ln -s /usr/bin/node /usr/bin/nodejs

This means that on your system, nodejs is really called node, so one possible remedy is to make a symbolic link.

**Comment by liciadep** [comment]
I do not have neither node or nodejs in bin forder. Could it has another name? how can I recognize this folder?

**Comment by magland** [comment]
To see if you have node installed:

node --version
or
nodejs --version

If it is not installed, then did you install nodejs according to the installation instructions? If so, how did you do it.

**Comment by liciadep** [comment]
I have this reply

RP720316:~ depropris.licia$ node --version
v6.11.3


so i think is intalled.

right?

what could be the error so?

**Comment by liciadep** [comment]
Hi, we made some step forward :0
now it is happy w nodejs, however when we try to run the example we get:

_Error in system call. Please be sure that mountainlab/bin is in your path._

despite mountainlab/bin it is indeed in our PATH: 
_RP720316:003_kron_mountainsort depropris.licia$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/depropris.licia/documents/GitHub/feel-free/mountainlab/bin_

Cheers for everything! Best

**Comment by magland** [comment]
That's good news! Did you successfully compile mountainlab using ./compile_components.sh?

if so, you should see things like mountainprocess in your mountainlab/bin/

**Comment by magland** [comment]
closed for lack of response.
