### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by fralik** [magland/mountainlab#163]
Hi!
Is there a documentation for developers regarding internal structures/design? From a quick look it seems that mountainlab uses all the cross platform tools, but then utilizes Unix signals which are much harder to copy over Windows.

**Comment by magland** [comment]
Yes, we don't aim to support windows. But we are developing web browser interfaces, and that is truly cross-platform. Although the expectation is that the actual data processing will be done on a Linux server.

On the other hand, the actual low-level processing routines are mostly written in C++/Qt5, so if you want to call those directly you can probably get that to work in windows.

Regarding developer docs, they are sparse, but I'll be happy to discuss the design on our slack channel.

**Comment by fralik** [comment]
Exactly! C++/Qt gives cross platform support out of the box. So I was surprised by a definitive no towards Windows.

I will be happy to join your Slack channel. My email is vadim.frolov@ntnu.no.

**Comment by wysota** [comment]
We are using some U*IX specific APIs in a number of places. They probably have their WinAPI equivalents so with some amount of work some of the processing and auxiliary tools could be ported to Windows. Some of the tools should already work in Windows. But making the whole suite Windows compliant is out of our reach now.

**Comment by fralik** [comment]
@wysota, is the specific API usage includes only signals? Or more things are used?

**Comment by wysota** [comment]
Signals is not really a problem - the range of signals we are using is covered by ANSI C standard so they are emulated by the C runtime on Windows as well. I can't tell off the top of my head but for example code related to process management and introspection uses info from `/proc`.

Software such as the viewer (mountainview) and supporting tools such as mda, prv and such should run on Windows out of the box. And we're working on the web frontend as well. For processing it might be feasible to run a Linux instance on Windows using VirtualBox and run server-side of MountainLab there.
