### ISSUE TITLE
firings.mda primary channels

### ISSUE THREAD

**Issue by peterlakatos** [magland/mountainlab#164]
Hi,

I ran my first sorting successfully, and the results displayed correctly, showing the distribution of units on the 23 recording contacts. However, when I export the firings to firings.mda and import to Matlab (using readmda.m), the first row of the file only contains zeros. Do you know what could be the problem?

Thank you in advance for your help. 
Peter Lakatos

**Comment by magland** [comment]
The first row is reserved for primary loading channel of the events, but algorithms are not required to supply that. Originally mountainsort output that information. Apparently it no longer does. We can look into the internal C++ source code to see why that is the case and whether it could be remedied. Let me know if you are interested in helping with that.

**Comment by peterlakatos** [comment]
Thank you Jeremy,

I'd love to help but I have no C++ programming knowledge. 
The reason why in our case primary channel location would be important is that we are using linear array electrodes and we can assign different channels to different cortical layers.

**Comment by magland** [comment]
One possibility is to derive this information from the templates (or average spike waveforms) by finding the channel with the peak signal for each cluster. I propose that we create a plugin processor that makes this calculation and outputs in the form of a cluster metric. This plugin could be in matlab or python.

**Comment by peterlakatos** [comment]
Thank you Jeremy, I was thinking the same.

**Comment by magland** [comment]
Great, let's pursue this when the time is right. In fact this is a property of cluster rather than event, so it kind of unnatural to include that row in the firings.mda. Nevertheless we are going to leave it the way it is, and maybe at some time in the future the first row would be used for some other specific purpose.
