### ISSUE TITLE
Spike width

### ISSUE THREAD

**Issue by mstux** [magland/mountainlab#165]
Hi,
I think my problem is that, when sorting, the program considers too many points before and after the peak of a spike. This causes the algorithm to include some noise and separate spikes that should be in the same cluster. How can I change the "width" to consider when sorting?
Thank you

**Comment by magland** [comment]
In your pipelines.txt use, for example, --clip_size_msec=1

If you are using the ms3 pipeline, you can see the list of set-able parameters in the ms3.pipeline file located at: mountainlab/packages/mountainsort3/algs

Note that this will not affect the clip size in the gui (mountainview)

**Comment by mstux** [comment]
Thank you!
