### ISSUE TITLE
Installing and Testing

### ISSUE THREAD

**Issue by gmbcrazy** [magland/mountainlab#166]
# Issue1 Installing.
**I was asked for GitHub username/password when I tried to clone mountainlab. I didn't success after setting my SSH key. Accidently, I copied following instruction from webpage directly, I made it. Though I have no idea how I got it. In general, it's installed by following the rest steps described in installing instructions.**

_git clone https://github.com/magland/mountainlab.git
cd mountainlab
git checkout ms3
./compile_components.sh_

# Issue2 Testing.
**I run the testing file as**

_cd examples/003_kron_mountainsort
./001_generate_synthetic_data.sh_
 
**I got following feedback at bottom. I think the key message is**

Error in system call. Please be sure that mountainlab/bin is in your path. 

**However, I do have this folder bin folder, and I tried the**

 “_export PATH=/path/to/moutainlab/bin:$PATH_” before testing.

# Whole error message:

Running mountainprocess run-process synthesize_timeseries_001_matlab --waveforms=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/waveforms.mda --timeseries=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/raw.mda --firings_true=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/firings_true.mda --M=4 --T=800 --K=16 --duration=1200 --amp_variation_min=0.2 --amp_variation_max=1 --firing_rate_min=0.5 --firing_rate_max=3 --noise_level=1
Process error: mountainprocess run-process synthesize_timeseries_001_matlab --waveforms=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/waveforms.mda --timeseries=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/raw.mda --firings_true=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/firings_true.mda --M=4 --T=800 --K=16 --duration=1200 --amp_variation_min=0.2 --amp_variation_max=1 --firing_rate_min=0.5 --firing_rate_max=3 --noise_level=1
{ [Error: spawn mountainprocess ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn mountainprocess',
  path: 'mountainprocess',
  spawnargs: 
   [ 'run-process',
     'synthesize_timeseries_001_matlab',
     '--waveforms=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/waveforms.mda',
     '--timeseries=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/raw.mda',
     '--firings_true=/home/singerlab/mountainlab/examples/003_kron_mountainsort/BIGFILES/example3/firings_true.mda',
     '--M=4',
     '--T=800',
     '--K=16',
     '--duration=1200',
     '--amp_variation_min=0.2',
     '--amp_variation_max=1',
     '--firing_rate_min=0.5',
     '--firing_rate_max=3',
     '--noise_level=1' ] }
Error in system call. Please be sure that mountainlab/bin is in your path.

**Comment by magland** [comment]
Regarding your PATH variable, please have a look at this issue discussion and see if that helps:
https://github.com/magland/mountainlab/issues/160

**Comment by gmbcrazy** [comment]
Thank you Jeremy,


I tried several combination of command to set the path and failed.


Actually ,I was using Virtual Machine for Linux on my PC.


On the command line, it represents as


singerlab@singerlab-Virtual-Machine:~$


which is the name of the virtual computer.


singerlab@singerlab-Virtual-Machine:~$ ls
Desktop  Documents  Downloads  mountainlab  Music  Pictures  Public  Templates  Videos
singerlab@singerlab-Virtual-Machine:~$

So I tried


export PATH=/mountainlab/bin:$PATH

and

export PATH=singerlab@singerlab-Virtual-Machine:~/path/to/mountainlab/bin:$PATH

many other commands. All failed.


Thank you for your patience


Best,

LU


________________________________
发件人: Jeremy Magland <notifications@github.com>
发送时间: 2017年9月27日 18:06
收件人: magland/mountainlab
抄送: Lu Zhang; Author
主题: Re: [magland/mountainlab] Installing and Testing (#166)


Regarding your PATH variable, please have a look at this issue discussion and see if that helps:
#160<https://github.com/magland/mountainlab/issues/160>

―

**Comment by magland** [comment]
you can run
echo $PWD
to get the absolute path of your current directory

**Comment by gitelian** [comment]
I got the same error when I tried to test. I later figured out that there was an error when I tried to compile. Did your compilation step succeed?

**Comment by gmbcrazy** [comment]
For compiling, there's no problem in my case.  I have no issues now to run the test files. 

Magland 's suggestion is great. As I'm running the Xunbutu on virtual machine of my PC, the home path is a little bit confusing.
