### ISSUE TITLE
Link about daemon

### ISSUE THREAD

**Issue by Min-SooKANG** [magland/mountainlab#167]
Hi. I would like to know what daemon is but the link with descriptions about daemon is dead.

Where can I get some explanations about daemon? What does it do?

Min Soo

**Comment by wysota** [comment]
A daemon is a process that runs in background. Simplifying it means a server.

**Comment by Min-SooKANG** [comment]
So it means there's no big difference in using which daemon?  Does using different daemon have no big effect on the result of automatic sorting?

**Comment by wysota** [comment]
You can't use a different daemon, you have to use the one which provides the functionality you need. Using a web server (which is also a daemon) will not give you ability to sort spikes. I cannot find the place in docs which you refer to, could you point me to it?

**Comment by Min-SooKANG** [comment]
Oh I was asking about the instructions for first sorting that says:

Before running the sorting you should start the processing daemon:
mp-daemon-start [name]
where [name] is the name of the daemon. Usually you would have only one of these running, so it could be your user name.

and in the instruction for installation says:
kron-run ms3 example1 --_nodaemon

and I just wanted to know whats these command lines mean!

**Comment by wysota** [comment]
The  name is optional, you don't have to pass anything.
