### ISSUE TITLE
mdaconvert specific channels

### ISSUE THREAD

**Issue by horsto** [magland/mountainlab#170]
Is there a way to combine the `mdaconvert` command with the `mdaconvert extract_channels` command?
I want to quickly convert .dat files with 16 channels to 4 tetrode .mda files. The way I would do that is to first convert the .dat file to a .mda file and then run `mdaconvert extract_channels ` on that file. Is there a better way?

**Comment by magland** [comment]
Unfortunately not at the moment. I'll put it on my todo list to add this capability.

**Comment by horsto** [comment]
thanks!
