### ISSUE TITLE
Nothing on cluster metrics

### ISSUE THREAD

**Issue by Min-SooKANG** [magland/mountainlab#172]
Hi. I have several questions about mountainsort.

After automatic sorting, I loaded the sorting results through the supported GUI.

But, nothing appears on the cluster metrics window. 

How can this problem be solved?

Min Soo

P.S. I guess maybe it's because automatic curation isn't applied. I see no difference between results before and after applying curation to pipeline. Also it seems clusters that violate the set threshold aren't rejected.

**Comment by Min-SooKANG** [comment]
Oh I figured it out!

**Comment by imyzx2017** [comment]
Hi @Min-SooKANG, I think I'm facing the same problem,I can only see the 'Timeseries' figure,and there is no other result.

How did you solve the problem?Could you give me some advice?

Thanks a lot.
