### ISSUE TITLE
bad_alloc

### ISSUE THREAD

**Issue by mstux** [magland/mountainlab#173]
Hi,
I get this error when sorting my data:

mountainsort.mountainsort3:: terminate called after throwing an instance of 'std::bad_alloc'

mountainsort.mountainsort3::   what():  std::bad_alloc

I'm trying to sort a few hours of recording from one channel. Any ideas why I get this error? If I run mountainsort on a shorter initial fraction of the data it works correctly.

Thank you

**Comment by wysota** [comment]
You are running out of RAM.

**Comment by mstux** [comment]
Thank you!
