### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by gitelian** [magland/mountainlab#175]
After cloning the repo and running `./compile_components.sh` the compilation process errors out leaving many of the critical methods such as ` mountainprocess, mdaconvert, mda, mountainview` unavailable. 

Please let me know if I can provide any additional information that may be helpful. Thank you.

Machine info:
Ubuntu 16.04 LTS
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

The output is in the attached file.
[compile_output.txt](https://github.com/magland/mountainlab/files/1356898/compile_output.txt)

**Comment by wysota** [comment]
Please remove Qt that comes with anaconda from your $PATH.

**Comment by gitelian** [comment]
I'm sorry but how can I do that without affecting my anaconda environments?
