### ISSUE TITLE
./compile_components on ms4 branch

### ISSUE THREAD

**Issue by horsto** [magland/mountainlab#176]
I just tried to run ./compile_components on the ms4 branch after git pull, but during the process I get error messages like: 
```
strip /home/hotte/mountainlab/bin/mp-spec
strip:/home/hotte/mountainlab/bin/mp-spec: File format not recognized
Makefile.mproc:348: recipe for target 'install_install0' failed
make[1]: [install_install0] Error 1 (ignored)
install -m 755 -p /home/hotte/mountainlab/cpp/mproc/bin_extra/procstat /home/hotte/mountainlab/bin/
strip /home/hotte/mountainlab/bin/procstat
strip:/home/hotte/mountainlab/bin/procstat: File format not recognized
Makefile.mproc:348: recipe for target 'install_install0' failed
make[1]: [install_install0] Error 1 (ignored)
```
and the command mp-list-processors give me messages like 
` mproc.processormanager  warning "Potential problem with executable processor file: /home/hotte/mountainlab/cpp/mlcommon/src/../../../packages/mlpython1/p_templates/p_templates.mp. Expected json output but got empty string."`
before putting out a list of processors like for example mountainsort.bandpass_filter, etc. 

Any ideas what could be wrong?

**Comment by magland** [comment]
I am not sure about the compile error, but for one of those errors please do the following:

Install python3 and python3-pip (pip3)

Then (in your python virtualenv if you are using one)
pip3 install numpy
pip3 install cppimport
pip3 pybind11

Let me know if it works once you have done that.

**Comment by horsto** [comment]
Thanks! The mp-list-processors command works now without warnings.

**Comment by magland** [comment]
Great!
