### ISSUE TITLE
No `prv-gui` in ms3 branch

### ISSUE THREAD

**Issue by ablot** [magland/mountainlab#179]
I installed `mountainsort` with no problem and clustered on of my dataset. Everything seems to work fine but there is no `prv-gui` in the bin folder and clicking on "Open PRV manager" in the GUI started by `kron-view` fails logically printing that in the console:

`===== sh: 1: prv-gui: not found`

Does `prv-gui` still exists?

**Comment by horsto** [comment]
Same problem here!

**Comment by magland** [comment]
Thanks for the report. That option is no longer supported, and so I will remove the button.
