### ISSUE TITLE
Error in converting to .mda file

### ISSUE THREAD

**Issue by imyzx2017** [magland/mountainlab#180]
Hi.My data(μV) is convert to .mda file successfully,but after sorting,except for 'Timeseries',no other results can be obtained.And here is my raw data size:
{
"data_type": -4,
"data_type_string": "int16",
"dims": [
1,
240000
],
"header_size": 20,
"num_bytes_per_entry": 2,
"num_dims": 2
}

How can this problem be solved?

Thanks a lot!

**Comment by magland** [comment]
Based on your raw data size, it appears you only have about 12 seconds of data (assuming 20 KHz). Is that expected? Could you please give some more detail by what you mean by "no other results can be obtained".

**Comment by imyzx2017** [comment]
Yes! Every spike train is made up of 10 seconds of data, and the samplerate is 24kHz.

when I do the sorting, I always got : Unexpected: Cluster is empty.

Then I compared the data files in 'datasets' folder with those in the 'mountainlab/examples/BIGFILE' folder. I found my data files is only a 'raw.mda' file, and were missing 'firings_true.mda' file and 'waveforms.mda'. 

So I think I have missed some of the processing steps. Are these two missing files necessary?

Could you give me some suggestions?Thanks a lot!

**Comment by magland** [comment]
I suspect the sorting algorithm failed because the dataset is too short for it to handle. It should fail more gracefully in this case. Typically spike sorting would be done on at least 10 minutes of data, in my experience.

**Comment by imyzx2017** [comment]
Thank you very much for taking the time to answer my questions!

I think the sorting algorithm can still works on my short dataset. For I‘ve just tried some methods, and finally get some results using ms3 branch.
the 'Cluster Detail' result  as follows: 132 spikes in cluster 1; 669 spikes in cluster 2. 

But there is still some problem.:
1. The 'Cluster Metrics' is empty. 
2. And I think I've got different result using 'wave_clus' software,  the reason is the that the spike shapes look different.
I think I need more time to solve those problems. 

And I have some questions:
1. Do I need to set up a lot of parameters? Like setting the thrshold.
2. If I may ask, compare to 'wave_clus', except for the advantage of clusters, is there any other automation in 'mountainlab'?

Could you give me some advices on my questions?Thanks!

**Comment by imyzx2017** [comment]
Sorry. I made a mistake in the second problem,
the spike shapes I got from 'wave_clus' and 'mountainlab' are the same.

**Comment by magland** [comment]
i am not familiar with wave_clus. I am not sure why cluster metrics is empty. Do you mean the cluster_metrics.json file is created but is empty?

**Comment by imyzx2017** [comment]
I think it was my mishandling that led to the 'cluster_metrics' in GUI did not display any information. And I think I can handle it.

And I have already read a paper proposed on 2004, it uesd a formula to calculate the threshold for mutil-channels: 
threshold = 4*median{x/0.6745} (x is the signal after bandpass filter)
But for my single-channel data, the effect of using the formula is not good.

So I'd like to ask you one more question at last:
How should I set the threshold? 

Thanks!!

**Comment by jasonechung** [comment]
If you are using the ms3 branch, I think that the default setting is to
*not* calculate the metrics; you will need to add the flag

--compute_metrics=true

to calculate the metrics. You can just add this flag and rerun - it should
skip the parts that it has already completed.

Also, you can set the detection threshold using the flag:

--detect_threshold=3.0

3.0 standard deviations is the default setting in the ms3.pipeline

**Comment by imyzx2017** [comment]
Yeah! I have fixed this problem, and get correct results.
Thank you all!

what I need to do next is to find a method to calculate the proper threshold for my single-channel datasets and then change the default setting on 'detect_threshold'. I will work on it.
