### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by gmbcrazy** [magland/mountainlab#181]
Hi, Magland,

Recenlty I use ms3.pipeline successfully sort my 32 channels proble data. In the viewer, it looks good and creat >40 clusters. But I have some questions towards the output files.

1. The raw data I have is continuous recording. I assume there's a waveform output in .mda format.  But I can't find it in the output folder. Is it created in the cron-viewer by exporting?

2. I tried to read out the output firings.mda in matlab.  However, the 3 rows matrix are completely zeros.

By the way, did you implement a refractory period parameter to delete some fake spikes?

Thank you 
Lu

**Comment by jasonechung** [comment]
Hi Lu,

I'm a little confused by what you mean by a refractory period parameter?
There is a detection interval lockout period for each channel - the default
value is 0.33 ms, and can be changed if you add the flag

--detect_interval_msec=0.33

to your pipeline.txt

1) There are no default waveform outputs - it is currently just the
firings.mda. That being said, there are probably other users who have some
code to grab the waveforms, and the waveform export will hopefully be added
at some later point... for now you will have to use the spike times to
extract the clips

2) Not sure what to say about the firings.mda if the GUI is loading the
clusters properly - is the firings.mda you are trying to read of a
reasonable file size?

Jason

**Comment by gmbcrazy** [comment]
Thanks a lot Jason.

For waveform, if I understand correctly, I could use the firing.mda to get timestamps/time index and extract the waveform from the filtered data.

0.33 is in microsecond? I might check the ISI when I am able to access to the timestamps data.  I asked the question is just because in Autocorregrogram of many neurons are not zero at time zero.

my firings.mda is 13MB as attached, is that possible that the readmda.m has a problem?

Thanks again.


LU
[firings.zip](https://github.com/magland/mountainlab/files/1383092/firings.zip)

**Comment by jasonechung** [comment]
Yes, this is correct in regards to getting clips out.

0.33 is in milliseconds, 10 samples if you are sampling at 30000

It is expected that there will be quite a few clusters of low quality /
multi-unit activity that have many refractory period violations - we hope
to use clean autocorrelograms as one of the ways to evaluate good clusters,
so building something systematic into the pipeline to ensure that they are
clean  is problematic.

How are you reading the mda file into matlab? Could you share the code?

When I just tried it on my end, I was able to get a reasonable output in
matlab just using

X=readmda('firings.mda');

**Comment by gmbcrazy** [comment]
Thanks a lot. 

The readmda.m I used is as attached, download here from a folder called "pebble-master".   I run matlab in windows, I assume this is not a problem.
[readmda.zip](https://github.com/magland/mountainlab/files/1383371/readmda.zip)

LU

**Comment by jasonechung** [comment]
Can you try manually opening the file:

F=fopen('/path/to/firings.mda','rb');
code=fread(F,1,'long')
numBytesPerEntry=fread(F,1,'long') 
numDims=fread(F,1,'long')
Dim1=fread(F,1,'long')
Dim2=fread(F,1,'long)

and verify that there is data there / share what the header reads?

If that works, 

Unfortunately I am unable to recreate this issue on my end - the readmda file should be working, and works on my end (linux/mac), windows should not be an issue - fopen and fread should be stable across OS and matlab versions

**Comment by gmbcrazy** [comment]
Hi, I think there's a error.  code = -7 in my case (both matlabs in windows and linux ), it doens't fall any case in later code:

"if (code==-1)
    M=zeros(1,N*2);
    M(:)=fread(F,N*2,'float');
    A(:)=M(1:2:prod(S)*2)+i*M(2:2:prod(S)*2);
elseif (code==-2)
    A(:)=fread(F,N,'uchar');
elseif (code==-3)
    A(:)=fread(F,N,'float');
elseif (code==-4)
    A(:)=fread(F,N,'short');
elseif (code==-5)
    A(:)=fread(F,N,'int');
end"

I doubted that we're using different version of readmda.m

**Comment by magland** [comment]
where is that readmda.m from?

It doesn't look the same as this one:

https://github.com/magland/mountainlab/blob/ms3/matlab/msutils/readmda.m

**Comment by gmbcrazy** [comment]
It looks alright now. Thanks a lot.  The "error" code is from following, which list at beginning when google. You might want to modify it or delete it.

https://github.com/magland/pebble/blob/master/readmda.m

**Comment by magland** [comment]
Thanks! I have a lot of old repos. Will need to clean them up.
