### ISSUE TITLE
Exit code 1 when running 001_generate_sythetic_data.sh

### ISSUE THREAD

**Issue by Selvanar** [magland/mountainlab#185]
Hello all! 

I am running into an issue when I run the 001_generate_synthetic_data.sh during step 3 of the installation instructions.

I get an exit code of '1'. More specifically I get the output - 

```
---------------------------------------------------------------
PROCESS COMPLETED (exit code = 1): synthesize_timeseries_001_matlab
ERROR: Exit code is non-zero: synthesize_timeseries_001_matlab
Peak RAM: 2 MB. Peak CPU: 0%. Avg CPU: 0%. Elapsed time: 1.003 seconds.
---------------------------------------------------------------
2017-10-17:12-47-30-535 mp.main critical Error in mountainprocessmain
"Exit code is non-zero: synthesize_timeseries_001_matlab"
```

I've followed every step exactly in the installation instructions with no errors or strange behavior until this point. I wasn't able to pinpoint what exactly was causing this issue or what an exit code of '1' refers to. Is this issue familiar with anyone? I am new to Linux so there is a possibility I have installed something incorrectly. I'm currently running Ubuntu on a virtual machine with octave instead of matlab. I've attached a [pdf](https://github.com/magland/mountainlab/files/1392708/exitCode1.pdf) with the full readout of the error.

I'd be happy to provide any additional information if you need it!

Thanks!

Max

**Comment by magland** [comment]
Which branch are you using? I would recommend that you use the ms3 branch for now.

**Comment by Selvanar** [comment]
I'm currently using the ms3 branch

**Comment by magland** [comment]
Could you try the 001 example? The 003 example depends on matlab or octave, and it is not always easy to determine why it might not be finding one or the other. I am taking the 003 example out of future releases.

**Comment by Selvanar** [comment]
the 001 example worked great! Thanks for your help
