### ISSUE TITLE
Error when sorting own data

### ISSUE THREAD

**Issue by peterzh** [magland/mountainlab#187]
Hi, 

I'm having some problems sorting my own dataset (385 channels, 5minutes of data at 30,000 samples per second). There seem to be no issues with the bandpass filtering or whitening, however I get the following error after this stage:

```
Processed 0.352 MB in 0.002 sec (176 MB/sec): Total 301.664 MB [Read data and add to neighborhood sorters] (2.17651%)...
Processed 0.352 MB in 0.002 sec (176 MB/sec): Total 302.016 MB [Read data and add to neighborhood sorters] (2.17905%)...
Processed 0.352 MB in 0.014 sec (25.1429 MB/sec): Total 302.368 MB [Read data and add to neighborhood sorters] (2.18159%)...
Processed 0.352 MB in 0.016 sec (22 MB/sec): Total 302.72 MB [Read data and add to neighborhood sorters] (2.18413%)...
Processed 0.352 MB in 0.004 sec (88 MB/sec): Total 303.072 MB [Read data and add to neighborhood sorters] (2.18667%)...
Processed 0.352 MB in 0.009 sec (39.1111 MB/sec): Total 303.424 MB [Read data and add to neighborhood sorters] (2.18921%)...
Processed 0.352 MB in 0.781 sec (0.450704 MB/sec): Total 303.776 MB [Read data and add to neighborhood sorters] (2.19175%)...
Processed 0.352 MB in 11.138 sec (0.0316035 MB/sec): Total 304.128 MB [Read data and add to neighborhood sorters] (2.19429%)...
/media/sf_C_DRIVE/MOUNTAINSORT_TEMP/mountainlab/tmp_short_term/ms.898703209.140344459155264.1366913857.tmp: line 13: 10644 Killed                  /home/peter/Desktop/mountainlab/packages/mountainsort3/bin/mountainsort3.mp mountainsort.mountainsort3 --geom= --timeseries=/media/sf_C_DRIVE/MOUNTAINSORT_TEMP/mountainlab/tmp_long_term/bade534852b1eb56f9990222a4649eaf02d7a604-mountainsort.whiten-timeseries_out.tmp --firings_out=/media/sf_C_DRIVE/MOUNTAINSORT_TEMP/mountainlab/tmp_long_term/ebcae794213cbd028e9fc9eb49ab6b46159e2522-mountainsort.mountainsort3-firings_out.tmp --adjacency_radius=1 --clip_size=50 --consolidate_clusters=true --consolidation_factor=0.8999999761581421 --detect_interval=9 --detect_sign=1 --detect_threshold=3 --fit_stage=true --merge_across_channels=true --t1=-1 --t2=-1 --_tempdir=/media/sf_C_DRIVE/MOUNTAINSORT_TEMP/mountainlab/tmp_short_term/tempdir_7B063SOL80

mountainsort.mountainsort3:: ---------------------------------------------------------------
PROCESS COMPLETED (exit code = 137): mountainsort.mountainsort3
ERROR: Exit code is non-zero: mountainsort.mountainsort3
Peak RAM: 3 MB. Peak CPU: 0%. Avg CPU: 0%. Elapsed time: 110.509 seconds.
---------------------------------------------------------------
2017-10-19:17-58-54-691	mp.main	critical	Error in mountainprocessmain "Exit code is non-zero: mountainsort.mountainsort3"

Process finished: mountainsort.mountainsort3

2017-10-19:17-58-55-930	mp.script_controller	warning	"Process returned with non-zero exit code: mountainsort.mountainsort3"


Peak Memory (MB):
  3.08 (mountainsort.bandpass_filter)
  3.076 (mountainsort.whiten)

Peak CPU percent:
  0 (mountainsort.bandpass_filter)
  0 (mountainsort.whiten)

Avg CPU (pct):
  0 (mountainsort.bandpass_filter)
  0 (mountainsort.whiten)

Elapsed time (sec):

  196.806 (mountainsort.bandpass_filter)
  1931.38 (mountainsort.whiten)
```

In case it's useful, here's the output from running 'mda' on my raw data file:

```
{
    "data_type": -4,
    "data_type_string": "int16",
    "dims": [
        385,
        9e+06
    ],
    "header_size": 20,
    "num_bytes_per_entry": 2,
    "num_dims": 2
}
```

I also don't use your write_mda function, because my original binary file is too big to load into memory. Therefore instead I manually create a header file with this matlab code:

```
outputFile = 'E:\raw_data\header.mda';
fout = fopen(outputFile,'w');
fwrite(fout,-4,'int32'); %-4 for int16, because my original binary data is int16
fwrite(fout,2,'int32'); %2 for number of bytes in each entry
fwrite(fout,2,'int32'); %2 dimensions (num channels by num timepoints)
fwrite(fout,385,'int32'); 
fwrite(fout,9e6,'int32'); 
fclose(fout);
```
I then concatenate this header with the original binary file, using cat:
`cat header.mda originalBinary.bin > raw.mda`

Thank you
Peter

**Comment by magland** [comment]
Hi Peter. That looks like a sensible thing to do to create .mda files.

Perhaps you are running out of RAM. How many CPU cores do you have? If too many, then you could run into a memory problem. There are ways to specify the number of parallel threads.

But I would recommend using a subset of the channels to start. In the ms4 branch there is are several useful processors, include pyms.extract_timeseries that let's you specify a subset of channels and time range. (There is also a similar processor in ms3 i believe)

**Comment by peterzh** [comment]
Thanks for the quick reply!

I tried increasing the RAM available, and reduced the cores from 4 to 2, and it worked.

Thank you,
Peter

**Comment by magland** [comment]
Great! Btw, with that many channels it's important to use a proper grom.csv with adjacent radius.

**Comment by peterzh** [comment]
Hi, I'm having trouble finding documentation for specifying the number of parallel threads. I presume it's a flag in the pipelines txt file?
Thanks!
Peter

**Comment by peterzh** [comment]
@magland Sorry to bother you, could you send me details for the slack channel ? I will have some more questions and I don't want to spam the issues board.
Thank you,
Peter

**Comment by magland** [comment]
Sure. And one way to set the number of threads globally is via the OMP_NUM_THREADS environment variable (will affect all omp-based processors, including the main sorting procedure).

Another way is through the --num_threads parameter in the pipelines.txt. You can see the parameters available for the ms3 pipeline here: https://github.com/magland/mountainlab/blob/ms3/packages/mountainsort3/algs/ms3.pipeline

**Comment by peterzh** [comment]
Great thank you very much
