### ISSUE TITLE
styling the entire app

### ISSUE THREAD

**Issue by magland** [magland/mountainlab#19]
Right now I am achieving a consistent color scheme across some of the widget using this type of code (see below). Need to handle this the right way. css? not sure.

QStringList color_strings;
    color_strings
        << "#282828"
        << "#402020"
        << "#204020"
        << "#202070";
    for (int i = 0; i < color_strings.count(); i++)
        d->m_channel_colors << QColor(brighten(color_strings[i], 80));

    d->m_colors["background"] = QColor(240, 240, 240);
    d->m_colors["frame1"] = QColor(245, 245, 245);
    d->m_colors["info_text"] = QColor(80, 80, 80);
    d->m_colors["view_background"] = QColor(245, 245, 245);
    d->m_colors["view_background_highlighted"] = QColor(210, 230, 250);
    d->m_colors["view_background_selected"] = QColor(220, 240, 250);
    d->m_colors["view_background_hovered"] = QColor(240, 245, 240);

    d->m_colors["view_frame_selected"] = QColor(50, 20, 20);
    d->m_colors["divider_line"] = QColor(255, 100, 150);

**Comment by wysota** [comment]
Doesn't look "the right way". However to suggest something different I would need to know what exactly you do with this code. An approach similar to what QPalette does (with color inheritance, etc.) seems right. Maybe you can use QPalette directly?

**Comment by magland** [comment]
To see how I use it, search for m_colors in:
https://github.com/magland/mountainlab/blob/master/mountainview/src/mvclusterdetailwidget.cpp
and in:
https://github.com/magland/mountainlab/blob/master/mountainview/src/histogramview.cpp
(in this way I achieve some consistency across the two widgets)

Here is a snippet from the latter:
 if (m_current) {
        painter.fillRect(R, m_colors["view_background_highlighted"]);
    }
    else if (m_selected) {
        painter.fillRect(R, m_colors["view_background_selected"]);
    }
    else if (m_hovered) {
        painter.fillRect(R, m_colors["view_background_hovered"]);
    }
    else {
        painter.fillRect(R, m_colors["view_background"]);
    }

If QPalette is the right way, could you direct me to how I could replace my code?

**Comment by wysota** [comment]
> If QPalette is the right way, could you direct me to how I could replace my code?

Off the top of my head (and it's just an example):
    QPalette palette = ...; // e.g. widget->palette();
    QPalette::ColorGroup group = (m_selected || m_current) ? QPalette::Active : QPalette::Inactive;
    QPalette::ColorRole role = QPalette::Base;
    painter.fillRect(R, palette.color(group, role));

If the roles and groups QPalette offers don't fit well into your expectations, we can implement a similar mechanism, just with a different set of attributes.

Alternatively there is QStyle API which is much richer and allows to perform more customized rendering based on values passed via QStyleOption objects. That's what Qt's model-view framework uses (have a look at QStyleOptionViewItem class).
