### ISSUE TITLE
Which branch to use

### ISSUE THREAD

**Issue by czawora** [magland/mountainlab#193]
Hello,

I am trying to follow the installation instructions and example sorts but seem to have to keep moving files around to the correct folders at every step of the way. I have been using the ms3 branch. Should I be doing something else?

Thanks

**Comment by czawora** [comment]
Currently at this point in the example sort
![screenshot 2017-10-26 14 23 03](https://user-images.githubusercontent.com/8885571/32070131-50833af4-ba59-11e7-8d8c-875fb5294d41.png)

**Comment by magland** [comment]
That's strange. Could you please do the 001_* example instead. The 003 example requires that octave or matlab is found properly, which is not always the case.

**Comment by czawora** [comment]
following the instructions.txt in 001_ example I get a similar result
![screenshot 2017-10-26 19 22 46](https://user-images.githubusercontent.com/8885571/32081406-345b7128-ba83-11e7-8887-56c1e064978a.png)

**Comment by magland** [comment]
Strange. Did the compile work okay? Can you please show the console output of ./compile_components.sh?

**Comment by czawora** [comment]
Compiling was not smooth. Many of the files needed for the compile were not located in the right directory or their locations were not included in the INCLUDE set. I had to run the following commands to make any progress compiling

cp cpp/mlcommon/include/mda/diskreadmda.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/get_sort_indices.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mda/mda.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mlcommon.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mlvector.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mda/mda32.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mda/mdaio.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mda/diskreadmda32.h cpp/mountainsort/src/utils/
cp cpp/mlcommon/include/mda/diskreadmda.h cpp/mountainsort/src/processors/
cp cpp/mlcommon/include/cachemanager/cachemanager.h cpp/mountainsort/src/processors/
cp cpp/mlcommon/include/mliterator.h cpp/mountainsort/src/isosplit/

I am attaching the compiler outputs at each of these steps
[compile_attempts.zip](https://github.com/magland/mountainlab/files/1428879/compile_attempts.zip)

**Comment by jasonechung** [comment]
Which linux distribution are you using?

**Comment by czawora** [comment]
I'm running on Mac Yosemite

**Comment by jasonechung** [comment]
Unfortunately, Mac is not supported yet. In the meantime, you can try running it in an ubuntu virtual machine. 
There are a few functions and libraries that are needed but are not included normally in MacOS such as sha1sum, and also other settings in Qt that would have to be modified, such as the build location for Qt. This is the reason why you are having to copy the location of the files.
