### ISSUE TITLE
Output re-calculating metrics after manual modification

### ISSUE THREAD

**Issue by gmbcrazy** [magland/mountainlab#195]
Hi Magland,

After manual modification  such as tag units as "reject, accepted" or merge several units into one neuron, I click the re-calculate all/visible, it looks like that the metrics doesn't update. 

And I also want to output those updated metrics to a .JSON file.

I wonder if those must be done by certain command line instead of working on the montainlab viewer.

Thanks a lot

LU

**Comment by magland** [comment]
Yes, it should be done by running certain processors on the new (curated) firings.mda. The relevant processors are:

ms3.cluster_metrics
ms3.isolation_metrics
ms3.combine_cluster_metrics

Another relevant processor: ms3.run_metrics_script

Sorry for lack of specifics. This stuff all needs to go into some clear docs.
