### ISSUE TITLE
Problems with mountainsort.whiten

### ISSUE THREAD

**Issue by EMNs** [magland/mountainlab#198]
Hi Jeremy, I keep on getting this error (code 136)... not sure what it is.. hope you can help me!

+++++++++++++++++++++++++++++++++++++++++++
{"name":"CSC12","folder":"raw_data/2017-06-08_10-07-22/csc12","absolute_folder_path":"./raw_data/2017-06-08_10-07-22/csc12","dataset_params":{"samplerate":32000,"sign":1},"arguments":[]}
{"name":"ms3","script":"ms3.pipeline","absolute_script_path":"/home/maria/mountainlab/kron/../packages/mountainsort3/algs/ms3.pipeline","pipeline_params":{"whiten":"true","detect_sign":"1","adjacency_radius":"100","compute_metrics":"true"},"arguments":[],"absolute_curation_script_path":""}
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
"run-script /home/maria/mountainlab/kron/../packages/mountainsort3/algs/ms3.pipeline ./raw_data/2017-06-08_10-07-22/csc12/params.json --raw=./raw_data/2017-06-08_10-07-22/csc12/raw.mda.prv --inpath=./raw_data/2017-06-08_10-07-22/csc12 --samplerate=32000 --sign=1 --whiten=true --detect_sign=1 --adjacency_radius=100 --compute_metrics=true --_nodaemon --outpath=output/ms3--CSC12 --_script_output=output/ms3--CSC12/pipeline_output.json"
Running mountainprocess run-script /home/maria/mountainlab/kron/../packages/mountainsort3/algs/ms3.pipeline ./raw_data/2017-06-08_10-07-22/csc12/params.json --raw=./raw_data/2017-06-08_10-07-22/csc12/raw.mda.prv --inpath=./raw_data/2017-06-08_10-07-22/csc12 --samplerate=32000 --sign=1 --whiten=true --detect_sign=1 --adjacency_radius=100 --compute_metrics=true --_nodaemon --outpath=output/ms3--CSC12 --_script_output=output/ms3--CSC12/pipeline_output.json
2017-11-28:11-40-36-947	cache_manager	warning	"2017-11-28 11:37:55" "2017-11-28 11:37:51" "/tmp/mountainlab/log/2017-11-28-level-warning"

2017-11-28:11-40-36-947	cache_manager	warning	Temporary file creation timestamp does not match that in the expiration record. Removing expiration record.
2017-11-28:11-40-36-948	cache_manager	warning	"2017-11-28 11:37:55" "2017-11-28 11:37:51" "/tmp/mountainlab/log/2017-11-28-cat-mp.script_controller"
2017-11-28:11-40-36-948	cache_manager	warning	Temporary file creation timestamp does not match that in the expiration record. Removing expiration record.
2017-11-28:11-40-36-948	cache_manager	warning	"2017-11-28 11:40:36" "2017-11-28 11:37:50" "/tmp/mountainlab/log/2017-11-28-cat-mp.main"
2017-11-28:11-40-36-948	cache_manager	warning	Temporary file creation timestamp does not match that in the expiration record. Removing expiration record.

SCRIPT: bandpass_filter: ./raw_data/2017-06-08_10-07-22/csc12/raw.mda.prv

SCRIPT: ################################# ./raw_data/2017-06-08_10-07-22/csc12/raw.mda.prv

2017-11-28:11-40-37-244	mp.script_controller	warning	"Unable to locate prv file originally at: raw.mda"

SCRIPT: Process already completed: mountainsort.bandpass_filter

Launching process mountainsort.whiten

2017-11-28:11-40-37-247	mp.script_controller	warning	"Unable to locate prv file originally at: raw.mda"

mountainsort.whiten:: STARTING: /home/maria/mountainlab/packages/mountainsort2/bin/mountainsort2.mp mountainsort.whiten --timeseries=/tmp/mountainlab/tmp_long_term/a9b9453118c4653bf3be690f32c8c01bb47809d4-mountainsort.bandpass_filter-timeseries_out.tmp --timeseries_out=/tmp/mountainlab/tmp_long_term/0b0959f1d3f20d467d120efb9e16fbe764f2f82a-mountainsort.whiten-timeseries_out.tmp --quantization_unit=0 --_tempdir=/tmp/mountainlab/tmp_short_term/tempdir_KQQ2CMXO0L .

mountainsort.whiten:: /tmp/mountainlab/tmp_short_term/ms.37149069.140149682383936.1942841066.tmp: line 13:  5347 Floating point exception(core dumped) /home/maria/mountainlab/packages/mountainsort2/bin/mountainsort2.mp mountainsort.whiten --timeseries=/tmp/mountainlab/tmp_long_term/a9b9453118c4653bf3be690f32c8c01bb47809d4-mountainsort.bandpass_filter-timeseries_out.tmp --timeseries_out=/tmp/mountainlab/tmp_long_term/0b0959f1d3f20d467d120efb9e16fbe764f2f82a-mountainsort.whiten-timeseries_out.tmp --quantization_unit=0 --_tempdir=/tmp/mountainlab/tmp_short_term/tempdir_KQQ2CMXO0L
---------------------------------------------------------------
PROCESS COMPLETED (exit code = 136): mountainsort.whiten
ERROR: Exit code is non-zero: mountainsort.whiten
Peak RAM: 0 MB. Peak CPU: 0%. Avg CPU: 0%. Elapsed time: 1,022 seconds.
---------------------------------------------------------------
2017-11-28:11-40-38-284	mp.main	critical	Error in mountainprocessmain "Exit code is non-zero: mountainsort.whiten"

Process finished: mountainsort.whiten

2017-11-28:11-40-39-352	mp.script_controller	warning	"Process returned with non-zero exit code: mountainsort.whiten"

Peak Memory (MB):

Peak CPU percent:

Avg CPU (pct):

**Comment by magland** [comment]
Thanks for the report. Which version of the software are you using, and would you be willing to try the most recent version on the flatironinstitute repo?

What is the size of your dataset (how many channels and timepoints?)

Does this error always occur at the same time? Does it run processing for a while and then stop? or does the error occur right away?

Could you check the available disk space in your temporary folder?

**Comment by EMNs** [comment]
Thank you for your quick reply!
I was using the latest version available (i installed mountainsort 1 month ago. I now installed the latest version, but I still get the same error. 
-I work with a 32 channel probe and record using neuralynx system. Neuralynx makes .ncs files and for each channel I get an independent file. So I am testing the program on just one channel, 157 Mb.
-The error always occurs at the same time, it runs really fast, and stops almost immediately.
- The space in the temporary folder is 73Gb..
Additional questions:
-for mlconfig utility do you need to pass any additional parameters or is there some documentation on how to use it and what does it do?
-just to double check, the raw/prv files have to be called raw.mda? they cannot be called anything else? I tried with the original file names and it would give me an error that it cannot find raw.mda.prv
Thanks in advance for your help!

**Comment by jasonechung** [comment]
mlconfig will prompt you for the input required to set the path(s) for 
1) The tmp directory where all the intermediate files (such as the whitened data) will live
2) The prv search paths - these are the paths/parent directories where the program will look for the files, regardless if they are renamed or moved from their original location

no, the raw files should not need to be called raw.mda, they can be passed in when calling the sort by using:
--raw=/path/to/your/raw/file.mda

Would you mind copy/pasting the console log from the new version?

**Comment by EMNs** [comment]
So I run it again and weirdly enough, it run without problems.. I did not do anything different, so Im a bit puzzled! the only thing I can think of, is that I restarted the computer.. so maybe that helped..so I guess problem solved. 
However, I do have 3 additional minor problems/questions
1) With regards to the mlconfig, it does not work. When I run the mlconfig command there is no ouput and nothing happens.
2) When I try to pass it the raw data (csc14.mda) this is what I do:
kron-run ms3 ---nodaemon --raw=/home/maria/Downloads/SBL_014/raw_data/2017-06-08_10-07-22/csc14.mda
this is what I get..
kron-run [pipeline_names] [dataset_names] --outpath=[output(default)] [--output-to-dataset-folder] [--_iff=intermediate_file_folder] [--_return]
3) Last question, as I was mentioning before, my raw data is divided in 32 output files, one per channel. I would like to run all the channels simultaneously, do you have a recommendation on how I could do that? 

Thanks a lot for your help!!

**Comment by magland** [comment]
I notice you are using kron. Please try to use the latest version of the software located at https://github.com/flatironinstitute/mountainsort

since we don't have the resources to troubleshoot multiple versions.

Does each channel get clustered separately?

**Comment by EMNs** [comment]
Yes each channel is clustered separately..

**Comment by EMNs** [comment]
Yes each channel is clustered separately..

**Comment by magland** [comment]
Let me know how installing the new version works. Regarding sorting the channels simultaneously... one way to do that is to specify a geometry file (geom.csv) and use a small adjacency_radius so that each channel gets sorted by itself.

**Comment by EMNs** [comment]
might be a stupid question, I did install the latest version of the software, but then what command should I use now to run this latest version? I cannot find any information on the new commands that I should be using..

**Comment by klaragerlei** [comment]
https://mountainsort.readthedocs.io/en/latest/

Following these instructions worked for me on the test data.

**Comment by EMNs** [comment]
I completely missed this info doc!! thank you for letting me know
