### ISSUE TITLE
Better visualization?

### ISSUE THREAD

**Issue by gmbcrazy** [magland/mountainlab#202]
Hi Magland,

We're using moutainlab in our lab. Basically it looks quite good.

Some of my colleagues asked the possibility to add an option to visual waveform according to geometric distribution of those channels using **Spiking Spray**, instead of showing waveform from Ch_1 to Ch_Last  from top to bottom?

Thanks a lot
LU

**Comment by magland** [comment]
Thanks for that suggestion. I will add it to the list, but don't have an estimated time at this point.
