### ISSUE TITLE
Error occurred when I ran the 001_ms4_jupyter_example file

### ISSUE THREAD

**Issue by kalfton** [magland/mountainlab#211]
Hi, 
I installed newest version of mountainlab in miniconda and I think I have followed every instructions in the readme files. But when I tried to run the first example file "001_ms4_jupyter_example" it throws error in the following cell block, which returned: "Exception: Error running process ms4alg.sort: Process returned with non-zero error code (255)". 
Do anyone knows how to solve it?
Thanks!
![screenshot from 2018-09-09 19-55-18](https://user-images.githubusercontent.com/36215989/45271178-a1453300-b46a-11e8-823f-40b7451ac6bd.png)
![screenshot from 2018-09-09 19-55-38](https://user-images.githubusercontent.com/36215989/45271179-a1453300-b46a-11e8-9752-c025baee414c.png)
![screenshot from 2018-09-09 19-56-46](https://user-images.githubusercontent.com/36215989/45271180-a1453300-b46a-11e8-90eb-ebd44c474c10.png)

**Comment by magland** [comment]
Hi, thanks for the report. Could you do me a favor and open this issue on the following repo instead?

https://github.com/flatironinstitute/mountainsort_examples

I will respond there. Meanwhile I am working on better console error reporting for this type of error.

**Comment by kalfton** [comment]
Sure, I have just opened an issue there
