### ISSUE TITLE
 NameError: name 'widgets' is not defined where running mountainsort example in Jupyter lab

### ISSUE THREAD

**Issue by Tousin1** [magland/mountainlab#212]
Hello @magland , I am working on the lastest version of mountainsort when I came across this problem:

NameError                                 Traceback (most recent call last)
<ipython-input-10-078a7e43fc0a> in <module>
      2 with Pipeline:
      3     #ironclust_sort_dataset(dataset_dir=dsdir,output_dir=output_dir,adjacency_radius=-1,detect_threshold=3)
----> 4     ms4_sort_dataset(dataset_dir=dsdir,output_dir=output_dir,adjacency_radius=-1,detect_threshold=3)

~/anaconda3/envs/mountainlab/lib/python3.6/site-packages/mountainlab_pytools/mlproc/mlproc_impl.py in __exit__(self, type, value, traceback)
     33         Global['current_client']=self._client
     34     def __exit__(self, type, value, traceback):
---> 35         self._client.run()
     36         Global['current_client']=None
     37 

~/anaconda3/envs/mountainlab/lib/python3.6/site-packages/mountainlab_pytools/mlproc/mlclient.py in run(self)
    185         #self._job_monitor.widget().clearJobs()
    186 
--> 187         self._status_out=widgets.Output()
    188         display(self._status_out)
    189         self._last_status_string=''

NameError: name 'widgets' is not defined

I know this is trying to call multiple modules in python from mountainlab evironment but i have no idea what the variable "widgets" means. Once again, I'm trying to test out the examples laid out on this website:

https://github.com/flatironinstitute/mountainsort_examples/blob/master/jupyter_examples/001_ms4_jupyter_example/ms4_jupyter_example.ipynb.

Could you help me without me manipulating the already written code modules?

Thanks,
Tousin

**Comment by Alkohost** [comment]
Please check the issue
https://github.com/flatironinstitute/mountainsort_examples/issues/14
