### ISSUE TITLE
Unable to stat file in prv_create

### ISSUE THREAD

**Issue by Tousin1** [magland/mountainlab#213]
I have a folder that has my geom.csv, params.json, and raw.mda. I wanted to create a .prv file for my raw data so that I can test sort it through the bash. However, an error message saying 'unable to stat file in prv_create'. I also tried using ml-prv-stat to no success. My raw file is about 1.6GB. 

Thanks for your work.

**Comment by dragospekic** [comment]
Hi Tousin1, could you let me know how you managed to cure this as I am getting the same message. Thanks!

**Comment by caitlinmallory** [comment]
Hi Tousin1 and dragospekic- I'm having this same issue. Have you solved it?
