### ISSUE TITLE
Error in saving image onto local computer

### ISSUE THREAD

**Issue by Tousin1** [magland/mountainlab#214]
Hey,

I successfully ran mountainsort on my data and it works well. However, I can't export or save the images it says I should contact you for help in the area. How could you help me with save images? Thanks alot. Thanks for releasing mountainsort version 4.

**Comment by magland** [comment]
Could you please explain what you mean by saving images?

**Comment by Tousin1** [comment]
I was trying to "save as" a selected name but won't let me. However, I figure i can just select "save" and it saves directly into my picture folder though i'll have to change the name manually. Problem solved. Thanks for responding.
