### ISSUE TITLE
mountainbrowser: "reload" menu entry does not reload

### ISSUE THREAD

**Issue by sebsgit** [magland/mountainlab#27]
to reproduce:
- run `mountainbrowser/bin/mountainbrowser`
- let the `experiments` list load
- right click on the main widget -> select `reload` option
- all `experiments` are gone now

this is printed in the console output:
```
JAVASCRIPT: "testing..."
JAVASCRIPT: "ReferenceError: Can't find variable: MB"
```

**Comment by magland** [comment]
Moved to new issue tracker
