### ISSUE TITLE
fit stage crash

### ISSUE THREAD

**Issue by ahbarnett** [magland/mountainlab#45]
Hi - running ms_devel/examples/driver_sort_EJnbhd.m
with jfm_april_sort
(making sure you have the dataset) causes segfault at fit stage.

*** FIT STAGE ***
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib /mnt/xfs1/home/ahb/spikesorting/mountainlab/matlab/processing/../../mountainsort/bin/mountainsort fit_stage --timeseries=/tmp/output/pre2.mda --firings=/tmp/output/firings2.mda --firings_out=/tmp/output/firings3.mda --use_old=0 --clip_size=50 --shell_increment=1.5 --min_shell_size=150
RUNNING fit_stage
pass 1: added 9169 events
pass 2: added 5578 events
pass 3: added 2710 events
pass 4: added 1106 events
pass 5: added 382 events
pass 6: added 114 events
pass 7: added 24 events
pass 8: added 4 events
pass 9: added 0 events
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib /mnt/xfs1/home/ahb/spikesorting/mountainlab/matlab/processing/../../mountainsort/bin/mountainsort fit_stage --timeseries=/tmp/output/pre2.mda --firings=/tmp/output/firings2.mda --firings_out=/tmp/output/firings3.mda --use_old=0 --clip_size=50 --shell_increment=1.5 --min_shell_size=150: Segmentation fault
Error using mscmd_fit_stage (line 15)
mountainsort returned with error status 139
Error in jfm_april_sort (line 137)
    mscmd_fit_stage([path,'/pre2.mda'],[path,'/firings2.mda'],[path,'/firings3.mda'],o_fit_stage);
    Error in driver_sort_EJnbhd (line 22)
[firingsfile,info] = jfm_april_sort(d.timeseries,d.outdir,opts);

**Comment by magland** [comment]
I believe I fixed this. Please confirm.

**Comment by ahbarnett** [comment]
confirmed
