### ISSUE TITLE
mv_closeall, ss_closeall

### ISSUE THREAD

**Issue by ahbarnett** [magland/mountainlab#46]
these don't close the open mv or spikespy windows. The issue is mv/bin/closeme.tmp is always 0 bytes, even after calling mv. Let me know if can provide debug output.

**Comment by magland** [comment]
First of all, is it a permissions issue? Matlab needs to be able to write to that temporary file in the same directory as the mountainview executable.

If that's not the problem, I created a debug branch. Please try the following.

checkout jfm-closeme-debug
mountainview/bin/mountainview

That will open an empty mountainview window.

On the console you should see a debug message every 1 second

Now from matlab:
mv_closeall

I assume mountainview will not close.

What do you see on the debug output?

**Comment by ahbarnett** [comment]
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"
DEBUG slot_timer closemehandler.cpp 41 CLOSEME 1
DEBUG slot_timer closemehandler.cpp 45 CLOSEME FILE EXISTS, CREATED AT "04-21-2016::11-58-24-000" START TIME IS "04-26-2016::10-14-09-536"

continual stream, unaffected by mv_closeall

**Comment by magland** [comment]
The file is not getting written for some reason. Could you look at mv_closeall.m?

It's like this:
function mv_closeall
mfilepath=fileparts(mfilename('fullpath'));
f=fopen([mfilepath,'/../../mountainview/bin/closeme.tmp'],'wb');
if (f>=0) fclose(f); end;
end

So you can see that it should be re-creating the file... You could do a
disp([mfilepath,'/../../mountainview/bin/closeme.tmp'])
to make sure it has the right file.

I suppose it should report an error if file is not opened.
