### ISSUE TITLE
 mountainview/src/sstimeseriesplot.cpp suspicious test

### ISSUE THREAD

**Issue by ahbarnett** [magland/mountainlab#48]
line 590 of  mountainview/src/sstimeseriesplot.cpp

  if ((t0 < 0) || (t0 < 0)) {
        P->fillRect(RR1, col2);
    }

I don't understand what the surrounding code does, but I'm sure something else was meant by the 2nd test.

**Comment by magland** [comment]
Created and merged pull request into master
